### ISSUE TITLE
Use the Intel VTune JIT Profiling API

### ISSUE THREAD

**Issue by StrikerX3** [fleroviux/lunatic#37]
The library allows the program to send information to VTune about JITted code so that we can profile programs without it losing track of the call stack. See documentation [here](https://www.intel.com/content/www/us/en/develop/documentation/vtune-help/top/api-support/jit-profiling-api/using-jit-profiling-api.html).

**Comment by fleroviux** [comment]
That looks interesting. Definitely will consider it!
