### ISSUE TITLE
X64Backend: Using cmp to implement cmn results in incorrect flags

### ISSUE THREAD

**Issue by MerryMage** [fleroviux/lunatic#4]
https://github.com/fleroviux/lunatic/blob/538a60f1d6c5bf835a92f7e690558e25f4045be0/src/backend/x86_64/backend.cpp#L481

Fairly sure this would break for the case of cmn against immediate zero.
You could expect a cmn with immediate zero to produce an unset carry flag, unfortunately this code results in a set carry flag.

**Comment by fleroviux** [comment]
Thanks!
